spring:
  datasource:
    url: jdbc:h2:mem:lg-test
    username: lg
    password: laundryGo!
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  enable-spring-security: false

logging:
  level:
    root: info
    com.laundrygo.shorturl.repository: debug