DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS url_mapping;

CREATE TABLE member
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE url_mapping
(
    id            BIGINT AUTO_INCREMENT PRIMARY KEY,
    original_url       TEXT       NOT NULL,
    short_url     VARCHAR(8) NOT NULL UNIQUE,
    request_count BIGINT    DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);